const {importStyle} = require("./core/utils/import-style");
const {CustomAttribute} = require('./core/parser/default-attributes/CustomAttribute');
const {engine} = require("./core/engine");
const {build} = require("./core/builder");
const {File} = require('./core/parser/File');
const {Element} = require('./core/parser/Element');
const {Text} = require('./core/parser/Text');
const {Comment} = require('./core/parser/Comment');
const {PartialFile} = require('./core/parser/PartialFile');

module.exports.CustomAttribute = CustomAttribute;
module.exports.File = File;
module.exports.PartialFile = PartialFile;
module.exports.Element = Element;
module.exports.Text = Text;
module.exports.Comment = Comment;
module.exports.engine = engine;
module.exports.build = build;
module.exports.importStyle = importStyle;
